use_default_settings: true

general:
  debug: false
  instance_name: "Local AI Search"

server:
  secret_key: "change-me"
  limiter: false
  image_proxy: true

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  formats:
    - html
    - json

redis:
  url: false

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  - name: brave
    engine: brave
    shortcut: br
    api_key: ""

  - name: wikipedia
    engine: wikipedia
    shortcut: wp

  - name: qwant
    engine: qwant
    shortcut: qw
